import type { PortfolioServiceTag, Project } from '@/lib/types';

/**
 * Unified portfolio — `/work` redesign + `/work/[slug]`.
 * First three entries stay the deep-dive mocks the homepage `CaseStudies` shows (unchanged order).
 */
export const projects: Project[] = [
  {
    id: 'northpeak-ai-onboarding',
    slug: 'northpeak-ai-onboarding',
    num: '01',
    industry: 'SaaS',
    country: 'Germany',
    clientType: 'SaaS · Germany',
    year: 2024,
    services: ['migrations', 'seo-performance', 'ai-agents', 'automation'],
    featured: true,
    deliveryTag: 'Next.js migration',
    title: 'NorthPeak — AI onboarding &',
    titleAccent: 'performance rebuild',
    pitch:
      'Replaced a slow marketing stack with a Next.js app that personalizes onboarding and routes leads automatically.',
    problem: 'slow pages, brittle tracking, manual lead triage.',
    solution:
      'Next.js App Router with strict TS, typed analytics, and n8n workflows for enrichment → routing → CRM sync.',
    metrics: [
      { value: '0.9s', label: 'LCP · from 8.2s' },
      { value: '-34%', label: 'bounce rate' },
      { value: '+180%', label: 'organic traffic' },
    ],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind', 'n8n', 'Vercel'],
    tag: 'Private',
    visual: 'mock',
    mockType: 'dashboard',
  },
  {
    id: 'heliocrm-automated-routing',
    slug: 'heliocrm-automated-routing',
    num: '02',
    industry: 'SaaS',
    country: 'UK',
    clientType: 'SaaS · UK',
    year: 2024,
    services: ['automation', 'refactoring'],
    featured: true,
    deliveryTag: 'Automation',
    title: 'HelioCRM — Automated enrichment &',
    titleAccent: 'lead routing',
    pitch:
      'Built an n8n pipeline that enriches leads, scores them, and routes to the right sales rep in under 30 seconds.',
    problem: 'manual enrichment via spreadsheets, inconsistent routing.',
    solution:
      'n8n with retries, dead-letter queues, Slack alerts, and full audit trail in Postgres.',
    metrics: [
      { value: '28h', label: 'saved / week' },
      { value: '<30s', label: 'routing SLA' },
      { value: '+18%', label: 'close rate' },
    ],
    techStack: ['n8n', 'Postgres', 'Clearbit', 'HubSpot', 'Slack'],
    tag: 'NDA',
    visual: 'mock',
    mockType: 'workflow',
  },
  {
    id: 'respondo-support-agent',
    slug: 'respondo-support-agent',
    num: '03',
    industry: 'SaaS',
    country: 'US',
    clientType: 'SaaS · US',
    year: 2025,
    services: ['ai-agents', 'automation', 'migrations'],
    featured: true,
    deliveryTag: 'AI agents',
    title: 'Respondo — Support agent on',
    titleAccent: 'product docs',
    pitch:
      'Shipped a safe AI assistant that answers from docs and performs scoped actions with full audit logs.',
    problem: 'repetitive tickets, inconsistent answers.',
    solution:
      'RAG pipeline with chunking, eval set, tool calling, and UI that makes confidence and sources explicit.',
    metrics: [
      { value: '-41%', label: 'tickets' },
      { value: '+0.6', label: 'CSAT' },
      { value: '38%', label: 'deflection' },
    ],
    techStack: ['Next.js', 'Claude API', 'RAG', 'pgvector', 'Vercel'],
    tag: 'Fast iteration',
    visual: 'mock',
    mockType: 'chat',
  },
  {
    id: 'aurora-commerce',
    slug: 'aurora-commerce',
    num: '04',
    industry: 'E‑commerce',
    country: 'EU',
    clientType: 'E‑commerce · EU',
    year: 2025,
    services: ['migrations', 'seo-performance'],
    featured: false,
    deliveryTag: 'Headless commerce',
    title: 'Aurora Commerce —',
    titleAccent: 'storefront rebuild',
    pitch: 'Headless storefront with sub‑second PLP and checkout tuned for mobile conversion.',
    problem: 'Legacy theme was slow, SEO fragmented, and promos required deploys.',
    solution: 'Next.js storefront, edge caching, and a CMS layer editors can ship without engineering.',
    metrics: [
      { value: '0.8s', label: 'LCP · PLP' },
      { value: '+22%', label: 'mobile CVR' },
      { value: '100', label: 'Lighthouse perf' },
    ],
    techStack: ['Next.js', 'Shopify', 'Tailwind', 'Vercel'],
    tag: 'Launch',
    visual: 'image',
    image: '/images/work/websites/website-01.webp',
    imageAlt: 'Aurora Commerce storefront screenshot',
  },
  {
    id: 'metricflow-analytics',
    slug: 'metricflow-analytics',
    num: '05',
    industry: 'B2B SaaS',
    country: 'US',
    clientType: 'B2B SaaS · US',
    year: 2025,
    services: ['automation', 'seo-performance', 'refactoring'],
    featured: false,
    deliveryTag: 'Marketing site',
    title: 'Metricflow —',
    titleAccent: 'demo hub & analytics',
    pitch: 'Marketing site + gated demo hub with consistent tracking and faster handoffs to sales.',
    problem: 'Fragmented forms, blind spots on which campaigns drove qualified demos.',
    solution: 'Unified lead model, server events, and n8n routing into CRM with SLA alerts.',
    metrics: [
      { value: '−41%', label: 'form drop‑off' },
      { value: '<2m', label: 'SLA to CRM' },
      { value: '12', label: 'locales' },
    ],
    techStack: ['Next.js', 'TypeScript', 'n8n', 'Postgres'],
    tag: 'Launch',
    visual: 'image',
    image: '/images/work/websites/website-02.webp',
    imageAlt: 'Metricflow marketing site screenshot',
  },
  {
    id: 'ledgerline-portal',
    slug: 'ledgerline-portal',
    num: '06',
    industry: 'FinTech',
    country: 'UK',
    clientType: 'FinTech · UK',
    year: 2024,
    services: ['migrations', 'refactoring', 'automation'],
    featured: false,
    deliveryTag: 'Client portal',
    title: 'Ledgerline —',
    titleAccent: 'secure client portal',
    pitch: 'Client portal for statements, tickets, and secure doc exchange with audit trail.',
    problem: 'Email-based support was opaque and compliance reviews were painful.',
    solution: 'Role-based portal, signed URLs, immutable activity log, and exportable reports.',
    metrics: [
      { value: 'SOC2', label: 'control mapping' },
      { value: '4.9★', label: 'CSAT portal' },
      { value: '−63%', label: 'email volume' },
    ],
    techStack: ['Next.js', 'Supabase', 'RLS', 'Vercel'],
    tag: 'NDA',
    visual: 'image',
    image: '/images/work/websites/website-03.webp',
    imageAlt: 'Ledgerline client portal screenshot',
  },
  {
    id: 'greenplate-landing',
    slug: 'greenplate-landing',
    num: '07',
    industry: 'Climate',
    country: 'Global',
    clientType: 'Climate · Global',
    year: 2026,
    services: ['seo-performance', 'migrations'],
    featured: false,
    deliveryTag: 'Campaign system',
    title: 'Greenplate —',
    titleAccent: 'landing system',
    pitch: 'Campaign landing system: reusable sections, localized copy, and crisp CWV scores.',
    problem: 'Each launch required a new static build and inconsistent brand blocks.',
    solution: 'Composable page builder pattern, MDX snippets, and image pipeline with AVIF/WebP.',
    metrics: [
      { value: '98', label: 'Lighthouse' },
      { value: '6', label: 'locales live' },
      { value: '2d', label: 'avg. ship time' },
    ],
    techStack: ['Next.js', 'MDX', 'Tailwind', 'Cloudinary'],
    tag: 'Launch',
    visual: 'image',
    image: '/images/work/websites/website-04.webp',
    imageAlt: 'Greenplate campaign landing screenshot',
  },
  {
    id: 'studiosync-portfolio',
    slug: 'studiosync-portfolio',
    num: '08',
    industry: 'Creative',
    country: 'Remote',
    clientType: 'Creative studio · Remote',
    year: 2024,
    services: ['seo-performance', 'refactoring'],
    featured: false,
    deliveryTag: 'Portfolio',
    title: 'Studiosync —',
    titleAccent: 'motion‑forward portfolio',
    pitch: 'Portfolio with cinematic motion (reduced-motion safe) and CMS-driven project grid.',
    problem: 'Flash-heavy old site hurt SEO and failed accessibility audits.',
    solution: 'CSS-first motion, content model for case studies, and static generation for speed.',
    metrics: [
      { value: 'AA', label: 'a11y target' },
      { value: '+3×', label: 'time on page' },
      { value: '0', label: 'layout CLS' },
    ],
    techStack: ['Next.js', 'Sanity', 'Motion', 'Vercel'],
    tag: 'Public',
    visual: 'image',
    image: '/images/work/websites/website-05.webp',
    imageAlt: 'Studiosync creative portfolio screenshot',
  },
  {
    id: 'healthread-app',
    slug: 'healthread-app',
    num: '09',
    industry: 'Health',
    country: 'India',
    clientType: 'Health · India',
    year: 2026,
    services: ['migrations', 'automation', 'refactoring'],
    featured: false,
    deliveryTag: 'Patient app',
    title: 'Healthread —',
    titleAccent: 'PWA shell',
    pitch: 'Patient-facing app shell: appointment booking, reminders, and multilingual UI.',
    problem: 'PWA felt native but bundle size and offline sync were unreliable.',
    solution: 'Route-based code splitting, service worker strategy, and optimistic UI for bookings.',
    metrics: [
      { value: '−38%', label: 'bundle size' },
      { value: '99.2%', label: 'uptime' },
      { value: '3', label: 'languages' },
    ],
    techStack: ['Next.js', 'PWA', 'Twilio', 'Supabase'],
    tag: 'Launch',
    visual: 'image',
    image: '/images/work/websites/website-06.webp',
    imageAlt: 'Healthread patient app screenshot',
  },
];

const SERVICE_CHIP_ORDER: PortfolioServiceTag[] = [
  'migrations',
  'ai-agents',
  'automation',
  'seo-performance',
  'refactoring',
];

export function uniquePortfolioServices(): PortfolioServiceTag[] {
  const set = new Set<PortfolioServiceTag>();
  for (const p of projects) {
    for (const svc of p.services) set.add(svc);
  }
  return SERVICE_CHIP_ORDER.filter((tag) => set.has(tag));
}
